#!/usr/bin/python3

from subprocess import Popen, PIPE, call
import re

ps = Popen("ps ax | grep proxyserver", shell=True, stdout=PIPE, stderr=PIPE).communicate()[0].decode("utf-8")

for l in ps.split("\n"):
    m=re.match(r"(\d+).*python3 .*proxyserver", l)
    if m:
        #stop a previous server
        call ("kill {}".format(m.group(1)), shell=True)
call("(translator/proxyserver &)", shell=True)
